flowchart TD
Org_cb695826_f7e5_4014_bc82_fc40f876f6af["Organization: ips_1000035712"]:::organization
Org_cb695826_f7e5_4014_bc82_fc40f876f6af --> VDC_urn_vcloud_vdc_e41a935d_4f99_4756_9013_0a2fc0f5df1a["VDC: com-b-ips_1000035712-01"]:::vdc
VDC_urn_vcloud_vdc_e41a935d_4f99_4756_9013_0a2fc0f5df1a --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d9f24f55_14f4_4cad_b46b_81a507f91801["vApp: Routing"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d9f24f55_14f4_4cad_b46b_81a507f91801 --> VM_urn_vcloud_vm_3aee62d8_3aff_4241_9c55_033c85e4f5e6["VM: DEFRA2-LRT01"]:::vm
VM_urn_vcloud_vm_3aee62d8_3aff_4241_9c55_033c85e4f5e6 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
VM_urn_vcloud_vm_3aee62d8_3aff_4241_9c55_033c85e4f5e6 --> Net_Ipsos_Voice_Network["Network: Ipsos-Voice-Network"]:::network
VDC_urn_vcloud_vdc_e41a935d_4f99_4756_9013_0a2fc0f5df1a --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_61521cd0_b527_4903_8e8f_e56adf4f2704["vApp: Netphone PBX"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_61521cd0_b527_4903_8e8f_e56adf4f2704 --> VM_urn_vcloud_vm_20910f5e_54c2_4ae7_9f50_bd3c23ba555b["VM: DEFRA2-PBX01"]:::vm
VM_urn_vcloud_vm_20910f5e_54c2_4ae7_9f50_bd3c23ba555b --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
Org_cb695826_f7e5_4014_bc82_fc40f876f6af --> VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451["VDC: com-a-ips_1000035712-01"]:::vdc
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_010d11a1_a344_48f8_8a87_90e600d68129["vApp: DEFRA2-LSAPP02a-a783d4b2-49c1-4207-849b-cf524771c77c"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_010d11a1_a344_48f8_8a87_90e600d68129 --> VM_urn_vcloud_vm_63db5c63_aa74_411f_9f52_78e982311272["VM: DEFRA2-LSAPP02"]:::vm
VM_urn_vcloud_vm_63db5c63_aa74_411f_9f52_78e982311272 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_362def72_8c42_4d47_8fa4_059614c128d0["vApp: CX"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_362def72_8c42_4d47_8fa4_059614c128d0 --> VM_urn_vcloud_vm_4637795a_8896_4e9b_9fd8_81e70a069f36["VM: DEFRA2-CXWEB02"]:::vm
VM_urn_vcloud_vm_4637795a_8896_4e9b_9fd8_81e70a069f36 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_a8f401e3_c939_464c_8e37_99043e053f7c["vApp: DEFRA2-WEB13-6cd5dd83-95ec-489a-b8f3-6261607a772c"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_a8f401e3_c939_464c_8e37_99043e053f7c --> VM_urn_vcloud_vm_b2eade33_8c8b_4328_b0ea_fb439ed01725["VM: DEFRA2-WEB13"]:::vm
VM_urn_vcloud_vm_b2eade33_8c8b_4328_b0ea_fb439ed01725 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_68058c8b_0daf_4666_b161_88bd159f66d2["vApp: DB-Hosting"]:::vapp
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_fda32472_ab40_4e9c_a402_3c7031fcbc34["vApp: Domain Controller"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_fda32472_ab40_4e9c_a402_3c7031fcbc34 --> VM_urn_vcloud_vm_978c2967_9327_4e75_ab41_0e74fa48138a["VM: DEFRA2-DC04"]:::vm
VM_urn_vcloud_vm_978c2967_9327_4e75_ab41_0e74fa48138a --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_fda32472_ab40_4e9c_a402_3c7031fcbc34 --> VM_urn_vcloud_vm_e4f4a892_4d84_41aa_88b7_4f916373b600["VM: DEFRA2-XDC01"]:::vm
VM_urn_vcloud_vm_e4f4a892_4d84_41aa_88b7_4f916373b600 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_fda32472_ab40_4e9c_a402_3c7031fcbc34 --> VM_urn_vcloud_vm_566dd0b8_b726_400c_9ac9_7861faaadc5a["VM: DEFRA2-DC05"]:::vm
VM_urn_vcloud_vm_566dd0b8_b726_400c_9ac9_7861faaadc5a --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_8749da62_4cd8_453c_9220_14f80dce1d22["vApp: EMEADELSTFS01"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_8749da62_4cd8_453c_9220_14f80dce1d22 --> VM_urn_vcloud_vm_5b382471_34e7_4f31_acc6_21c577a3a2e1["VM: EMEADELSTFS01"]:::vm
VM_urn_vcloud_vm_5b382471_34e7_4f31_acc6_21c577a3a2e1 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_0c872795_9796_4fc3_8829_78d1320781fc["vApp: DEFRA2-SQL05_restore"]:::vapp
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_6399d761_5b51_4166_bd2b_db010065e411["vApp: restore_new"]:::vapp
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d1d5fa58_ce83_47e0_9de1_521786de2bb4["vApp: BE Apps"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d1d5fa58_ce83_47e0_9de1_521786de2bb4 --> VM_urn_vcloud_vm_16854f70_e57e_4610_b2a1_702ccbbefb75["VM: DEFRA2-WEB02"]:::vm
VM_urn_vcloud_vm_16854f70_e57e_4610_b2a1_702ccbbefb75 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
VM_urn_vcloud_vm_16854f70_e57e_4610_b2a1_702ccbbefb75 --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d1d5fa58_ce83_47e0_9de1_521786de2bb4 --> VM_urn_vcloud_vm_27d3c8fc_9e80_47f8_a78f_f238787c2599["VM: DEFRA2-FP03"]:::vm
VM_urn_vcloud_vm_27d3c8fc_9e80_47f8_a78f_f238787c2599 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d1d5fa58_ce83_47e0_9de1_521786de2bb4 --> VM_urn_vcloud_vm_21867e84_00f9_4828_a310_5fe659633bf7["VM: DEFRA2-BEAPP01"]:::vm
VM_urn_vcloud_vm_21867e84_00f9_4828_a310_5fe659633bf7 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d1d5fa58_ce83_47e0_9de1_521786de2bb4 --> VM_urn_vcloud_vm_bfa0a224_0054_4045_8273_5a208c6d84f8["VM: leu-wwwintra01 (web+DB)"]:::vm
VM_urn_vcloud_vm_bfa0a224_0054_4045_8273_5a208c6d84f8 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_58f64ba0_cfb4_44c6_b4c4_84670e734460["vApp: ERM"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_58f64ba0_cfb4_44c6_b4c4_84670e734460 --> VM_urn_vcloud_vm_27e5497e_72dd_4548_80eb_e9bcd08167c7["VM: DEFRA2-SQL02"]:::vm
VM_urn_vcloud_vm_27e5497e_72dd_4548_80eb_e9bcd08167c7 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_58f64ba0_cfb4_44c6_b4c4_84670e734460 --> VM_urn_vcloud_vm_6fc3e8df_185e_48d9_a173_b21f0c584fc4["VM: DEFRA2-WEB04"]:::vm
VM_urn_vcloud_vm_6fc3e8df_185e_48d9_a173_b21f0c584fc4 --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
VM_urn_vcloud_vm_6fc3e8df_185e_48d9_a173_b21f0c584fc4 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d1cb0975_6610_4b02_93da_c0ac1b07d209["vApp: Ukraine-Service"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d1cb0975_6610_4b02_93da_c0ac1b07d209 --> VM_urn_vcloud_vm_7b6063b6_ea6a_41b8_aa8a_f63c7aaaa31f["VM: euua-pc06"]:::vm
VM_urn_vcloud_vm_7b6063b6_ea6a_41b8_aa8a_f63c7aaaa31f --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d1cb0975_6610_4b02_93da_c0ac1b07d209 --> VM_urn_vcloud_vm_ced97ab1_c63c_4bdb_8bb5_05606181bb44["VM: EUUA-PC14"]:::vm
VM_urn_vcloud_vm_ced97ab1_c63c_4bdb_8bb5_05606181bb44 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d1cb0975_6610_4b02_93da_c0ac1b07d209 --> VM_urn_vcloud_vm_7e622413_24fc_45b3_9d5e_8a6e28856414["VM: euua-pc23"]:::vm
VM_urn_vcloud_vm_7e622413_24fc_45b3_9d5e_8a6e28856414 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d1cb0975_6610_4b02_93da_c0ac1b07d209 --> VM_urn_vcloud_vm_da98b3c7_73d1_4e75_a645_c4a53778e107["VM: euua-pc07"]:::vm
VM_urn_vcloud_vm_da98b3c7_73d1_4e75_a645_c4a53778e107 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_d1cb0975_6610_4b02_93da_c0ac1b07d209 --> VM_urn_vcloud_vm_ab27b6d9_f71d_49d8_987a_470c6ca08568["VM: DEFRA2-FP05"]:::vm
VM_urn_vcloud_vm_ab27b6d9_f71d_49d8_987a_470c6ca08568 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_3ffdeac2_d70c_4c3b_9946_a6f7d6ce44fe["vApp: DE-WEB-PUBLIC"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_3ffdeac2_d70c_4c3b_9946_a6f7d6ce44fe --> VM_urn_vcloud_vm_277040be_be4e_4e6d_80b7_773f42189a60["VM: DEFRA2-XMAIL01"]:::vm
VM_urn_vcloud_vm_277040be_be4e_4e6d_80b7_773f42189a60 --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
VM_urn_vcloud_vm_277040be_be4e_4e6d_80b7_773f42189a60 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_3ffdeac2_d70c_4c3b_9946_a6f7d6ce44fe --> VM_urn_vcloud_vm_d3635bd4_38ae_40d1_9e37_d3e94de74679["VM: DEFRA2-XWEB03"]:::vm
VM_urn_vcloud_vm_d3635bd4_38ae_40d1_9e37_d3e94de74679 --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
VM_urn_vcloud_vm_d3635bd4_38ae_40d1_9e37_d3e94de74679 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_3ffdeac2_d70c_4c3b_9946_a6f7d6ce44fe --> VM_urn_vcloud_vm_915ee0e4_d496_4c75_bc0d_a37778876573["VM: DEFRA2-WEB09"]:::vm
VM_urn_vcloud_vm_915ee0e4_d496_4c75_bc0d_a37778876573 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
VM_urn_vcloud_vm_915ee0e4_d496_4c75_bc0d_a37778876573 --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_3ffdeac2_d70c_4c3b_9946_a6f7d6ce44fe --> VM_urn_vcloud_vm_c1562a45_6c1c_4b38_8f35_217c8db47bc8["VM: DEFRA2-XWEB11-T"]:::vm
VM_urn_vcloud_vm_c1562a45_6c1c_4b38_8f35_217c8db47bc8 --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
VM_urn_vcloud_vm_c1562a45_6c1c_4b38_8f35_217c8db47bc8 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_3ffdeac2_d70c_4c3b_9946_a6f7d6ce44fe --> VM_urn_vcloud_vm_0bb784ec_5acc_4cdf_95bf_e7fa20e0d505["VM: fileXchange"]:::vm
VM_urn_vcloud_vm_0bb784ec_5acc_4cdf_95bf_e7fa20e0d505 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
VM_urn_vcloud_vm_0bb784ec_5acc_4cdf_95bf_e7fa20e0d505 --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_3ffdeac2_d70c_4c3b_9946_a6f7d6ce44fe --> VM_urn_vcloud_vm_0c63c4e6_2632_42c4_85a7_d8e1865f9a83["VM: DEFRA2-XWEB11"]:::vm
VM_urn_vcloud_vm_0c63c4e6_2632_42c4_85a7_d8e1865f9a83 --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
VM_urn_vcloud_vm_0c63c4e6_2632_42c4_85a7_d8e1865f9a83 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_3ffdeac2_d70c_4c3b_9946_a6f7d6ce44fe --> VM_urn_vcloud_vm_b595a66a_1ca0_4af0_a391_c27d66416bef["VM: DEFRA2-WEB08"]:::vm
VM_urn_vcloud_vm_b595a66a_1ca0_4af0_a391_c27d66416bef --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
VM_urn_vcloud_vm_b595a66a_1ca0_4af0_a391_c27d66416bef --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_3ffdeac2_d70c_4c3b_9946_a6f7d6ce44fe --> VM_urn_vcloud_vm_aac883bf_c712_448b_bead_b7103ef07287["VM: DEFRA2-WEB05"]:::vm
VM_urn_vcloud_vm_aac883bf_c712_448b_bead_b7103ef07287 --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
VM_urn_vcloud_vm_aac883bf_c712_448b_bead_b7103ef07287 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_781a45dd_1250_44e6_90da_2df2cac5ba6a["vApp: F2F"]:::vapp
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_7e71e6a8_0c37_4aa0_a1b2_beddb94f864d["vApp: DE-CSS"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_7e71e6a8_0c37_4aa0_a1b2_beddb94f864d --> VM_urn_vcloud_vm_f5c903d6_db30_4578_bc72_7299285ef2c0["VM: DEFRA2-DSRPRD1"]:::vm
VM_urn_vcloud_vm_f5c903d6_db30_4578_bc72_7299285ef2c0 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_7e71e6a8_0c37_4aa0_a1b2_beddb94f864d --> VM_urn_vcloud_vm_6aeef0f6_bf0b_45b1_b746_84cbefa0263d["VM: DEFRA2-APPJRA02"]:::vm
VM_urn_vcloud_vm_6aeef0f6_bf0b_45b1_b746_84cbefa0263d --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_7e71e6a8_0c37_4aa0_a1b2_beddb94f864d --> VM_urn_vcloud_vm_bb685367_26bf_45b2_aa67_a598ed57f053["VM: DEFRA2-DSRDEV1"]:::vm
VM_urn_vcloud_vm_bb685367_26bf_45b2_aa67_a598ed57f053 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_14fb4c29_997c_43e2_be03_d49fb3cca2b6["vApp: digiPharm"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_14fb4c29_997c_43e2_be03_d49fb3cca2b6 --> VM_urn_vcloud_vm_18d0e51f_d10f_4d76_97cc_09a69dd87cc9["VM: DEFRA2-SQL01"]:::vm
VM_urn_vcloud_vm_18d0e51f_d10f_4d76_97cc_09a69dd87cc9 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_14fb4c29_997c_43e2_be03_d49fb3cca2b6 --> VM_urn_vcloud_vm_50fda18d_3478_426d_b033_4ca5e7fb2ad6["VM: DEFRA2-WEB01"]:::vm
VM_urn_vcloud_vm_50fda18d_3478_426d_b033_4ca5e7fb2ad6 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_14fb4c29_997c_43e2_be03_d49fb3cca2b6 --> VM_urn_vcloud_vm_9555ab4e_add3_4063_bef9_90cdc9bf0599["VM: spxx-aphcrs01-staging"]:::vm
VM_urn_vcloud_vm_9555ab4e_add3_4063_bef9_90cdc9bf0599 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
VM_urn_vcloud_vm_9555ab4e_add3_4063_bef9_90cdc9bf0599 --> Net_none["Network: none"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_14fb4c29_997c_43e2_be03_d49fb3cca2b6 --> VM_urn_vcloud_vm_18b29bb9_6833_4241_9453_4d5add7446d6["VM: ipxx-aphcrs01"]:::vm
VM_urn_vcloud_vm_18b29bb9_6833_4241_9453_4d5add7446d6 --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
VM_urn_vcloud_vm_18b29bb9_6833_4241_9453_4d5add7446d6 --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_14fb4c29_997c_43e2_be03_d49fb3cca2b6 --> VM_urn_vcloud_vm_f94d3a0e_90dd_494b_96c6_b8a82b96480d["VM: DEFRA2-DIGIWEB"]:::vm
VM_urn_vcloud_vm_f94d3a0e_90dd_494b_96c6_b8a82b96480d --> Net_Public_external_GW02["Network: Public_external_GW02"]:::network
VM_urn_vcloud_vm_f94d3a0e_90dd_494b_96c6_b8a82b96480d --> Net_DMZ_internal_GW05["Network: DMZ_internal_GW05"]:::network
VDC_urn_vcloud_vdc_dbf89116_5ee5_4040_b727_56f5c6f12451 --> vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688["vApp: Internal Server"]:::vapp
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_63c9fd60_e2d8_4185_8417_fcc365dccd43["VM: DEFRA2-FP02-NEW"]:::vm
VM_urn_vcloud_vm_63c9fd60_e2d8_4185_8417_fcc365dccd43 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_793d73a0_cc38_489f_ac70_fe68abc0df95["VM: DEFRA2-WEB12"]:::vm
VM_urn_vcloud_vm_793d73a0_cc38_489f_ac70_fe68abc0df95 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_e27d5fe7_2777_4589_887f_11188b0635f3["VM: DEFRA2-WEB12-T"]:::vm
VM_urn_vcloud_vm_e27d5fe7_2777_4589_887f_11188b0635f3 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_73558383_3474_41ff_82b6_c23666dec2eb["VM: DEFRA2-SQL04"]:::vm
VM_urn_vcloud_vm_73558383_3474_41ff_82b6_c23666dec2eb --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_c632ab66_1e50_4ac7_9b73_b89cc6235196["VM: DEFRA2-FP04"]:::vm
VM_urn_vcloud_vm_c632ab66_1e50_4ac7_9b73_b89cc6235196 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_2660c7fe_1dc9_4c39_9b71_0907b4177396["VM: DEMLN1-PDQAPP01"]:::vm
VM_urn_vcloud_vm_2660c7fe_1dc9_4c39_9b71_0907b4177396 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_6d7508ea_8c3a_445d_8146_7194bb907305["VM: DEFRA2-TS03"]:::vm
VM_urn_vcloud_vm_6d7508ea_8c3a_445d_8146_7194bb907305 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_1fb65f5c_be4b_4446_98d9_f727958f2ab3["VM: DEFRA2-APP03"]:::vm
VM_urn_vcloud_vm_1fb65f5c_be4b_4446_98d9_f727958f2ab3 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
VM_urn_vcloud_vm_1fb65f5c_be4b_4446_98d9_f727958f2ab3 --> Net_none["Network: none"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_2e4b32d8_1744_46a8_a82b_217975546259["VM: DEMLN1-NAVAPP01"]:::vm
VM_urn_vcloud_vm_2e4b32d8_1744_46a8_a82b_217975546259 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_0da8991b_d996_4558_8993_706eb2265303["VM: DEFRA2-PRC02"]:::vm
VM_urn_vcloud_vm_0da8991b_d996_4558_8993_706eb2265303 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_4457c653_1a2e_4c2a_923e_65218c03b9e5["VM: DEFRA2-SQL03"]:::vm
VM_urn_vcloud_vm_4457c653_1a2e_4c2a_923e_65218c03b9e5 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_115ad3f4_32c3_4c13_9f8e_126fa5e3788e["VM: DEFRA2-WEB10"]:::vm
VM_urn_vcloud_vm_115ad3f4_32c3_4c13_9f8e_126fa5e3788e --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_35634058_de5d_4caf_af1b_e5dbafb64ded["VM: DEMLN1-PRINTAPP"]:::vm
VM_urn_vcloud_vm_35634058_de5d_4caf_af1b_e5dbafb64ded --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_2564c339_e88d_4c05_9c7c_9f94829ca572["VM: DEFRA2-TS01"]:::vm
VM_urn_vcloud_vm_2564c339_e88d_4c05_9c7c_9f94829ca572 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_ad4feb15_be95_4c8e_9912_71ca340b0215["VM: EMEADEMLNSTR1"]:::vm
VM_urn_vcloud_vm_ad4feb15_be95_4c8e_9912_71ca340b0215 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_c67c1863_c00b_4511_9dfe_8b2209f4560e["VM: DEFRA2-SQL05"]:::vm
VM_urn_vcloud_vm_c67c1863_c00b_4511_9dfe_8b2209f4560e --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_bcf3c3ce_bb19_4052_be68_8c1c590c0b41["VM: DEMLN1-UPD01"]:::vm
VM_urn_vcloud_vm_bcf3c3ce_bb19_4052_be68_8c1c590c0b41 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_ebf5e48b_ed56_45f6_bc68_581895538227["VM: DEFRA2-WEB06"]:::vm
VM_urn_vcloud_vm_ebf5e48b_ed56_45f6_bc68_581895538227 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_633cf861_68ae_4621_8163_b677c1e7b83e["VM: DEFRA2-DP01"]:::vm
VM_urn_vcloud_vm_633cf861_68ae_4621_8163_b677c1e7b83e --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network
vApp_https_//vcloud_ffm_private.t_systems.de/api/vApp/vapp_59f5f1b2_7f63_4c1a_a49b_f364a5b7c688 --> VM_urn_vcloud_vm_d4ac298b_fedf_469a_838a_39326d6f62b2["VM: DEFRA2-FP01"]:::vm
VM_urn_vcloud_vm_d4ac298b_fedf_469a_838a_39326d6f62b2 --> Net_Ipsos_internal_GW05["Network: Ipsos_internal_GW05"]:::network

classDef organization fill:#ffcc00,stroke:#000,stroke-width:2px;
classDef vdc fill:#ccffcc,stroke:#000,stroke-width:2px;
classDef vapp fill:#ccccff,stroke:#000,stroke-width:2px;
classDef vm fill:#ffcccc,stroke:#000,stroke-width:2px;
classDef network fill:#ffffcc,stroke:#000,stroke-width:2px;
